language: python
os: linux
python:
- '2.7'
- '3.6'
- '3.9'
install:
- pip install -r requirements.txt
script:
- python setup.py test
stages:
- name: test
  if: repo = "vgrem/Office365-REST-Python-Client"
- name: deploy
jobs:
  include:
  - stage: deploy
    python: 3.6
    deploy:
      provider: pypi
      username: vgrem
      skip_existing: true
      password:
        secure: 6m1/PyNSzjHkZg4zNVjUePdNY3s/Aq/Ucsk69hKVpp5N3dgJGQQOyogwbGr27ezsbiKnK/Ek3AiUVftsWQhjc4PwZjMNAizQh5jt3pywWsghg5sA8rigKlZ+Fx1koAcmD6uxLiEZ83z42XQRyi3Ewsnjx+Hc6r1yQE07tK6AjMEtY/Vq03QU+cAQ8EA7QItulp+b5XEVythK/TVnfoIUxx1EkyMGsT6wjLO43kRnWWTy23dfV0EvgMLM4xXbEqcVRigWxoU2yUYGAbb3TwQ6WBAGBf+G2OdF46XiB5IgIyI/ik5F4+1LZpJUCLxynTT3NyRs3jtZ1t7Xv3xC9xTYT121bVut3D/79HHdvKf4yHMpI6Qxs3Si+3+iOM0G3uaPMcax8fskus7QTAnUDJrMP04y1qfT/3i+GMyYsIhLLnZjlLlHv85IT91OWqVjqkGxxUZa2oHiwyck2w0VOkKyWfIV7EdE2owlWrhW8ui/xMLEAaBvRmG2lyEM/mncJT4RwTbgqw/CUdVXDYbZc/cJzKDzqWS5e92Js/zyPWqYcxY9VM3WgcJP3YzcPbnxgL0bO8qj3uDlLuLvCL1e/x/fcktM4VtZAPK2/9vz1aJ/Ac9TDZTSy7Fi4oN02gfuOWoCHXbg74FflSlRa5Ug3pf9S7cpvxb2jRbiRPpG+AY/3rs=
      on:
        tags: true
        python: 3.6
        repo: vgrem/Office365-REST-Python-Client
